### ISSUE TITLE
feature request: add option to run tasks sequentially

### ISSUE THREAD

**Issue by zkx5xkt** [tinylibs/tinybench#17]
Running a second task in a parallel to the one being benchmarked may affect the benchmark results for both tasks.

**Comment by Aslemammad** [comment]
ok, could you please give some examples, references?

**Comment by Aslemammad** [comment]
Ok, I'll try working on this soon.

**Comment by FINDarkside** [comment]
I don't think this should be an option it should be on by default. Right now all the benchmarks results are incorrect unless you use the sequential version. I didn't really look how this lib is implemented but running multiple benchmarks at the same time make any of the results invalid as seen by the code posted by @zkx5xkt
