### ISSUE TITLE
Feature: add JS runtime information to `Bench` and benchmark results 

### ISSUE THREAD

**Issue by jerome-benoit** [tinylibs/tinybench#173]
## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/tinylibs) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/tinylibs/tinybench/issues/173">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/tinylibs/tinybench/issues/173/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/tinylibs/tinybench/issues/173/pledge.svg">
</picture>
</a>

**Comment by sikehish** [comment]
I'd love to take this up, but would love for some more clarity before that :)
