### ISSUE TITLE
Sequential benchmarks should be the default

### ISSUE THREAD

**Issue by FINDarkside** [tinylibs/tinybench#21]
This library introduced sequential benches in  #18, but there really shouldn't be any other kind of benches. Running multiple benchmarks at the same time means that they are are fighting for the same cpu time, especially since the benches aren't even launched in their own threads.

Running non-sequential benchmarks is pointless because the results are always going to be wrong unless the benchark is completely synchronous in which case they will run sequentially despite the api used or you are testing some external server and each bench tests different server. I think the examples in readme should use the sequential api and possibly the the non-sequential api should just be removed.

**Comment by Aslemammad** [comment]
I see, We'll work on this soon.
