### ISSUE TITLE
Is there a reason that bench.run() doesn't throw?

### ISSUE THREAD

**Issue by jcbhmr** [tinylibs/tinybench#47]
I was scratching my head for a good three hours until I did this:

```js
bench.addEventListener("error", e => reportError(e))
```

Scenario:

```js
const bench = new Bench()
bench.add("i look fast but i just fail", () => { iDontExist() })
await bench.run()
console.table(bench.table())
```

Is there a reason that right now throwing inside benchmarks doesn't cause a catastrophic failure? There must  be... right? 😅

I think that it would be a good idea to make it so that either:
1. bench.run() throws
2. console.error() on any errors

Some kind of user feedback that the superfast speeds they're seeing are actually _an error_ is a good idea. 😊

**Comment by Aslemammad** [comment]
Yes, because environemnts like Vitest want to handle the error themselves instead of us throwing. We can add an option called `throws`, that'd also be good.

**Comment by Aslemammad** [comment]
check #51

**Comment by jdmarshall** [comment]
I've been dealing with this the last couple of days. If you look at bench.tasks (for instance, when bench.table() is being called) you can see that some of your tests ran 0 times, and the result contains the error it encountered.  

It would be better for everyone who is not us if the tests told you when they are blowing up.

**Comment by Aslemammad** [comment]
I fixed this in the PR and I'll try to merge soon, sorry for the delay!

**Comment by jdmarshall** [comment]
The extra checks in table() might fix a problem I'm having. cool cool

**Comment by Aslemammad** [comment]
Happy to hear that @jdmarshall
