### ISSUE TITLE
Documentation: create TypeDoc site?

### ISSUE THREAD

**Issue by jcbhmr** [tinylibs/tinybench#48]
This is a feature request. You can close this as "Not planned" and I won't feel bad, don't worry ❤️

I think that the current setup with an `examples/` folder and a bunch of docs that feel very shallow. They're also somewhat duplicated across the hover in-IDE intellisense (the .d.ts files) and the readme would be better consolidated into a single place: a documentation website. There's enough content that I think it's worth the effort (and the effort isn't much 😊)

```jsonc
// package.json
{
  "scripts": {
    "build:docs": "typedoc"
  },
  "typedoc": {
    "entryPoints": ["src/index.ts"]
    "out": "sitedocsdistplacefolder/name/here",
    "skipErrorChecking": true
  }
}
```

And then you can use GitHub Actions to deploy it to GitHub Pages in about 5 minutes of typey-types

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/tinylibs) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/tinylibs/tinybench/issues/48">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/tinylibs/tinybench/issues/48/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/tinylibs/tinybench/issues/48/pledge.svg">
</picture>
</a>

**Comment by barelyhuman** [comment]
Workaround for now: https://typeapi.barelyhuman.dev/pkg/tinybench
