### ISSUE TITLE
Move types/index.d.ts to src/types.ts

### ISSUE THREAD

**Issue by jcbhmr** [tinylibs/tinybench#49]
![image](https://github.com/tinylibs/tinybench/assets/61068799/50e95c27-88ea-43f3-8c30-a475bf4bef0f)
https://www.youtube.com/watch?v=zu-EgnbmcLY
Basically this 👆 by Matt Pocock https://www.mattpocock.com/

Summary of my own interpretation of it: .d.ts is for typescript types with an associated .js "real file". They often get excluded from type checking due to `skipLibCheck: true`, which can be _not good_. The recommended solution appears to be: just use normal .ts files. TypeScript will remove all the type code (since that's what `tsc` does after all 😉) and the import will be dropped entirely since it was all just types. Thus, the same end result.

**Comment by Aslemammad** [comment]
Nice, learned something new. Please send a PR if you want.

**Comment by Aslemammad** [comment]
@jcbhmr It's being done in #51 

Thank you so much.
