### ISSUE TITLE
Can tinybench generate `browser-performance.json`-formatted output?

### ISSUE THREAD

**Issue by stdedos** [tinylibs/tinybench#60]
Example: https://gitlab.com/gitlab-org/gl-performance

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/tinylibs) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/tinylibs/tinybench/issues/60">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/tinylibs/tinybench/issues/60/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/tinylibs/tinybench/issues/60/pledge.svg">
</picture>
</a>

**Comment by Aslemammad** [comment]
That's a nice thing to have, but maybe another repo should be created as a plugin, because I dont want to make tinybench the opposite of tiny.

**Comment by jerome-benoit** [comment]
Won't be part of tinybench.

**Comment by stdedos** [comment]
Please close as _won't do_ :pray:
