### ISSUE TITLE
When used with Vitest, tinybench produces results too different from other tools like mitata

### ISSUE THREAD

**Issue by sheremet-va** [tinylibs/tinybench#70]
Mitata shows a x15 diff with the slowest option, vitest only a x2.

Reproduction: https://stackblitz.com/edit/node-odkzk5?file=package.json,tests%2Fexample.bench.ts
Related: https://github.com/vitest-dev/vitest/issues/2220

**Comment by sirenkovladd** [comment]
https://github.com/vitest-dev/vitest/issues/2220#issuecomment-1949889895

**Comment by Aslemammad** [comment]
@sirenkovladd Thank you so much for the exploration!

**Comment by sheremet-va** [comment]
Thank you for investigating this issue! I will close it then.
