### ISSUE TITLE
Concurrent benchmarking

### ISSUE THREAD

**Issue by t3dotgg** [tinylibs/tinybench#74]
I was hoping to do some testing of how JS frameworks perform when getting multiple requests at a time. A concurrency limit flag would be dope.

Did some reading of [past issues](https://github.com/tinylibs/tinybench/issues/21) and I don't fully agree with the removal of the previous parallel options. Surely it won't be perfectly accurate, but no benchmark is

**Comment by Aslemammad** [comment]
Hey Theo. Yea it makes sense, one of the reasons was that it was using so many resources so thought maybe it's not ideal at all. 

I can add an option called `{ concurrency: boolean | number }` or a new method called `runConcurrently(number)`.

**Comment by t3dotgg** [comment]
Slightly leaning towards the alternative runner but I'd default to your judgement @Aslemammad !

**Comment by Aslemammad** [comment]
Just released `v2.7.0`, let me know if there's any issue.
