### ISSUE TITLE
Feature request: `name` field in `Bench`

### ISSUE THREAD

**Issue by colinhacks** [tinylibs/tinybench#81]
I was writing a custom prettyprinter for tinybench and found myself wishing there was a way to attach a `name` field to a `Bench` instance. 

```ts
new Bench({
  name: "my benchmark"
})
```

That way, I could have a self-contained logger function that I can pass a `Bench` instance into:

```ts
function myLogger(bench: Bench){
  console.log(bench.name);
  console.table(bench.table());
}
```

Happy to put in a PR if I get a greenlight from a maintainer 👍

**Comment by Aslemammad** [comment]
Let's have this one! 🚀
